appName: demo-minikube

deployment:
  replicaCount: 1
  image:
    repoitory: docker.io/tembleking/demo-minikube:latest
    pullPolicy: Always

service:
  type: ClusterIP

ingress:
  create: true
  host: foo.com
  path: /